blank_issues_enabled: true
contact_links:
  - name: Discord ğŸ‘¾
    url: https://chat.tangleswap.exchange
    about: Join our community for discussion and support.
  - name: Twitter ğŸ¤
    url: https://twitter.com/TangleSwap
    about: Follow the latest announcements to stay up-to-date.